Repository Enkelt/Enkelt-Dev, pull requests merged in 2019-08, with the labels that each got.

#32 Ändrade hur Enkelt-kod körs så att det ska fungera på windows
  Exempel/test.e
  enkelt.py
  run_enkelt.py
Labels: bug

#33 lagt till nya funktioner för listor, close #21
  run_enkelt.py
Labels: enhancement

#37 lagt till typ(), close #34
  enkelt.py
  run_enkelt.py
Labels: enhancement

#40 fixade tom rad i kod bug, close #35
  run_enkelt.py
Labels: bug

#42 fixat töm på linux
  run_enkelt.py
Labels: bug

#43 fixa legacy töm på linux
  run_enkelt.py
Labels: bug

#45 Fixade problemet med att göra funktionsanrop från en annan funktion.
  Exempel/test.e
  final_transpiled.py
  run_enkelt.py
Labels: bug

#46 Gjorde för och medan till funktioner, lade till support för +=
  Exempel/test.e
  run_enkelt.py
Labels: bug, enhancement

#47 lagt till tidsfunktioner #44
  Exempel/test.e
  run_enkelt.py
Labels: enhancement

#48 lagt till många mattefunktioner
  run_enkelt.py
Labels: enhancement

#52 Lade till lexikon (dictionaries) som variabeldatatyp.
  Exempel/test.e
  run_enkelt.py
Labels: enhancement

#53 Lade till enumerate() -> numrera() för för-loopar med listor
  Exempel/test.e
  run_enkelt.py
Labels: enhancement

#49 lagt till datumsfunctioner #44 och fixat problem med e, e --> matte_e
  run_enkelt.py
Labels: bug, enhancement

#55 Lade till mera unittests, fixade användarfunktioner, gjorde nyckelordslexing bättre
  Exempel/test.e
  run_enkelt.py
  test_enkelt.py
Labels: bug, enhancement

#58 Lade till och och eller
  Exempel/test.e
  run_enkelt.py
Labels: enhancement

#56 Börjat lägga till importera
  Exempel/abc.e
  Exempel/test.e
  bib/importtest.e
  enkelt.py
  importera-how-to.txt
  libs/importtest.e
  run_enkelt.py
Labels: enhancement

#60 Fixade in() prompten
  EnkeltModules.py
  Exempel/test.e
  enkelt.py
  run_enkelt.py
  test_enkelt.py
Labels: bug

#61 Enkelt is now one file, fixes & improvements
  EnkeltModules.py
  enkelt.py
  run_enkelt.py
  test_enkelt.py
Labels: bug, enhancement

#62 You can now enable developer/debug mode by use the '--d' flag when running enkelt.py
  enkelt.py
Labels: bug

#65 lagt till importering från weben
  Exempel/test.e
  enkelt.py
  libs/importtest.e
Labels: enhancement

#68 Stavfel, små fixar
  lib.py
Labels: enhancement

#69 lagt till filer
  Exempel/test.e
  enkelt.py
Labels: enhancement
