Repository Enkelt/Enkelt-Dev, pull requests merged in 2020-07, with the labels that each got.

#139 Variable operators bug fix
  Exempel/test.e
  enkelt.py
Labels: bugg

#140 Minor readability changes and decreasing cyclomatic complexity of lex()
  enkelt.py
  test_enkelt.py
Labels: förbättring

#143 Changed och --> &, eller --> |, and inte --> !
  enkelt.py
Labels: bugg, fel, förbättring
